packages:
  - 'packages/*'
  - 'apps/*'
  - 'apps/clients/*'

allowBuilds:
  better-sqlite3: false
  esbuild: true

catalog:
  '@types/node': '24.13.3'
  '@trpc/client': '11.18.0'
  '@trpc/server': '11.18.0'
  fastify: '5.11.3'
  superjson: '2.2.6'
  tsx: '4.23.12'
  typescript: '5.9.3'
  zod: '3.25.76'
  dotenv: '17.4.2'
  p-queue: '9.3.3'
  toad-scheduler: '4.1.0'
  '@types/better-sqlite3': '9.6.0'
  better-sqlite3: '13.0.3'
  drizzle-orm: '0.38.4'
  drizzle-kit: '0.30.6'
